### PR TITLE
Close #1. First working version

### LINKED ISSUE #1: PHP_CodeSniffer Support
_From @muuvmuuv on June 20, 2018 12:4_

**Beautifier Details**
Name: PHP_CodeSniffer (phpcs)
Link to project/homepage: https://github.com/squizlabs/PHP_CodeSniffer

**If this is to update an existing beautifier, please describe what should be updated**
currently, in PHP just php-cs-fixer is supported, but phpcs also supports auto fixing with the `phpcbf ` command. It would be nice to support phpcs too

Languages Supported: PHP
How is it run (node, terminal, etc): PHP terminal with `phpcs <file> <options>`

_Copied from original issue: Unibeautify/unibeautify#110_

### PR DESCRIPTION
**Pull request by Glavin001**
See https://github.com/Unibeautify/beautifier-php-codesniffer/issues/1

@muuvmuuv please take a look at this PR. Let us know if you have any questions or concerns. This is only the first working version and more features will be sure to come later.

Tasks
- [x] Run `phpcbf`
- [ ] Support `prefer_beautifier_config` should pass config file to `--standard=/path/to/ruleset.xml`

### CODE REVIEW

**Comment by szeck87** [comment]
Why is CodeClimate disabled?

**Comment by Glavin001** [comment]
@szeck87 I couldn't figure out how to find the CodeClimate page.

If I go to https://codeclimate.com/oss/dashboard
I only see:
image

I wasn't sure if the CodeClimate `CC_TEST_REPORTER_ID` was correct and then realized I had no idea how to even find the correct value. Could you give me a hand? How are the other repositories setup and why can I not see them?

**Comment by szeck87** [comment]
Click the "Add a repository" button at the top.  It should be listed on the next page (do a sync with GitHub if it's not).  Once you add it go to the Settings for it, and the ID should be there.

**Comment by Glavin001** [comment]
@szeck87 I thought I tried that before and it didn't work. I hit `Sync` this time though so maybe that helped. Got it working now. Thanks!

**Comment by muuvmuuv** [comment]
I would like to test it, how do I create a test environment?

I tried a little bit yet; added the compiled output to `/node_modules/@unibeautify/beautifier-php-codesniffer`, added it to beautifiers.ts `import phpCodesniffer from "@unibeautify/beautifier-php-codesniffer";` and run `tsc`again. But I always get `Error: Beautifier not found: PHP_CodeSniffer`

**Comment by Glavin001** [comment]
@muuvmuuv Your steps sound good. You may have missed adding to `beautifiers` array: https://github.com/Unibeautify/vscode/blob/master/src/beautifiers.ts#L9

I expect the resulting file to look like:

```typescript
import { Beautifier } from "unibeautify";
import prettyDiff from "@unibeautify/beautifier-prettydiff";
import prettier from "@unibeautify/beautifier-prettier";
import jsBeautify from "@unibeautify/beautifier-js-beautify";
import eslint from "@unibeautify/beautifier-eslint";
import phpCsFixer from "@unibeautify/beautifier-php-cs-fixer";
import clangFormat from "@unibeautify/beautifier-clang-format";
import phpCodesniffer from "@unibeautify/beautifier-php-codesniffer"; // <---- NEW

export const beautifiers: Beautifier[] = <any[]>[
  prettier,
  jsBeautify,
  prettyDiff,
  eslint,
  phpCsFixer,
  clangFormat,
  phpCodesniffer, // <---- NEW
];
```

I'm going to publish to [VSCode extension](https://github.com/Unibeautify/vscode) soon 🎉 . Then you can test it out there 😃.

**Comment by Glavin001** [comment]
Website: https://github.com/Unibeautify/website/pull/102
VSCode: https://github.com/Unibeautify/vscode/pull/56

**Pull request merged**
